In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])
print(arr1)
print(type(arr1))

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(type(arr2))

arr3 = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]] )
print(arr3)
print(type(arr3))

[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


In [8]:
print(np.zeros((2)))
print(np.ones((3, 2))) 
np.empty((2,3))
arr4 = np.arange(0, 10, 2, dtype=np.int64)
arr4

[0. 0.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([0, 2, 4, 6, 8])

In [10]:
arr5 = np.random.random([5,5])
print(arr5)
print(type(arr5))

arr6 = np.random.randint(0,10,(2,2))
print(arr6)
print(type(arr6))

arr7 = np.random.uniform(0,1,(2,2))
print(arr7)
print(type(arr7))

[[0.26719208 0.47149836 0.95633803 0.20947916 0.25695061]
 [0.1074059  0.99079241 0.77042558 0.32153872 0.46335828]
 [0.98610202 0.1035699  0.51215623 0.95497614 0.29590646]
 [0.62173949 0.39065469 0.50386638 0.03528702 0.9540744 ]
 [0.78049249 0.6490606  0.31584026 0.15691711 0.19988365]]
<class 'numpy.ndarray'>
[[6 4]
 [5 2]]
<class 'numpy.ndarray'>
[[0.38447063 0.29770081]
 [0.50898167 0.52159284]]
<class 'numpy.ndarray'>


In [11]:
arr8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr8.shape)
print(arr8.ndim)
print(arr8.dtype)
print(arr8.size)

(3, 3)
2
int64
9
